// Mermaid theme 설정
// src/styles/tailwind-color-schemes.css color scheme 변수와 동기화

import type { ColorScheme } from "@/lib/color-schemes";

export interface MermaidThemeVars {
    primaryColor: string;
    primaryTextColor: string;
    primaryBorderColor: string;
    lineColor: string;
    secondaryColor: string;
    secondaryTextColor: string;
    secondaryBorderColor: string;
    tertiaryColor: string;
    tertiaryTextColor: string;
    tertiaryBorderColor: string;
    background: string;
    mainBkg: string;
    textColor: string;
    noteBkgColor: string;
    noteTextColor: string;
}

// 스킴별 테마 (light/dark), tailwind-color-schemes.css 동기화
export const MERMAID_THEMES: Record<
    ColorScheme,
    { light: MermaidThemeVars; dark: MermaidThemeVars }
> = {
    slate: {
        light: {
            primaryColor: "#e6eaf0",
            primaryTextColor: "#141620",
            primaryBorderColor: "#c5cad4",
            lineColor: "#5c6370",
            secondaryColor: "#dbeafe",
            secondaryTextColor: "#141620",
            secondaryBorderColor: "#c5cad4",
            tertiaryColor: "#f3f5f8",
            tertiaryTextColor: "#141620",
            tertiaryBorderColor: "#c5cad4",
            background: "#f3f5f8",
            mainBkg: "#e6eaf0",
            textColor: "#141620",
            noteBkgColor: "#dbeafe",
            noteTextColor: "#141620",
        },
        dark: {
            primaryColor: "#22252e",
            primaryTextColor: "#e4e8f0",
            primaryBorderColor: "#2e3340",
            lineColor: "#8890a0",
            secondaryColor: "#1a2540",
            secondaryTextColor: "#e4e8f0",
            secondaryBorderColor: "#2e3340",
            tertiaryColor: "#1a1c24",
            tertiaryTextColor: "#e4e8f0",
            tertiaryBorderColor: "#2e3340",
            background: "#1a1c24",
            mainBkg: "#22252e",
            textColor: "#e4e8f0",
            noteBkgColor: "#1a2540",
            noteTextColor: "#e4e8f0",
        },
    },
    ember: {
        light: {
            primaryColor: "#f2ede6",
            primaryTextColor: "#2a2118",
            primaryBorderColor: "#ddd5ca",
            lineColor: "#7a6f62",
            secondaryColor: "#ffedd5",
            secondaryTextColor: "#2a2118",
            secondaryBorderColor: "#ddd5ca",
            tertiaryColor: "#faf8f5",
            tertiaryTextColor: "#2a2118",
            tertiaryBorderColor: "#ddd5ca",
            background: "#faf8f5",
            mainBkg: "#f2ede6",
            textColor: "#2a2118",
            noteBkgColor: "#ffedd5",
            noteTextColor: "#2a2118",
        },
        dark: {
            primaryColor: "#28201a",
            primaryTextColor: "#f0ebe4",
            primaryBorderColor: "#3d3228",
            lineColor: "#9a918a",
            secondaryColor: "#2e2010",
            secondaryTextColor: "#f0ebe4",
            secondaryBorderColor: "#3d3228",
            tertiaryColor: "#1c1814",
            tertiaryTextColor: "#f0ebe4",
            tertiaryBorderColor: "#3d3228",
            background: "#1c1814",
            mainBkg: "#28201a",
            textColor: "#f0ebe4",
            noteBkgColor: "#2e2010",
            noteTextColor: "#f0ebe4",
        },
    },
    circuit: {
        light: {
            primaryColor: "#e0f2e8",
            primaryTextColor: "#0f2618",
            primaryBorderColor: "#b0d4be",
            lineColor: "#4a7058",
            secondaryColor: "#dcfce7",
            secondaryTextColor: "#0f2618",
            secondaryBorderColor: "#b0d4be",
            tertiaryColor: "#f2faf5",
            tertiaryTextColor: "#0f2618",
            tertiaryBorderColor: "#b0d4be",
            background: "#f2faf5",
            mainBkg: "#e0f2e8",
            textColor: "#0f2618",
            noteBkgColor: "#dcfce7",
            noteTextColor: "#0f2618",
        },
        dark: {
            primaryColor: "#162018",
            primaryTextColor: "#daf0e2",
            primaryBorderColor: "#1e3828",
            lineColor: "#70a880",
            secondaryColor: "#102818",
            secondaryTextColor: "#daf0e2",
            secondaryBorderColor: "#1e3828",
            tertiaryColor: "#0e1612",
            tertiaryTextColor: "#daf0e2",
            tertiaryBorderColor: "#1e3828",
            background: "#0e1612",
            mainBkg: "#162018",
            textColor: "#daf0e2",
            noteBkgColor: "#102818",
            noteTextColor: "#daf0e2",
        },
    },
    phantom: {
        light: {
            primaryColor: "#ede8f8",
            primaryTextColor: "#1a1030",
            primaryBorderColor: "#c8bce0",
            lineColor: "#665c80",
            secondaryColor: "#ede9fe",
            secondaryTextColor: "#1a1030",
            secondaryBorderColor: "#c8bce0",
            tertiaryColor: "#f8f5ff",
            tertiaryTextColor: "#1a1030",
            tertiaryBorderColor: "#c8bce0",
            background: "#f8f5ff",
            mainBkg: "#ede8f8",
            textColor: "#1a1030",
            noteBkgColor: "#ede9fe",
            noteTextColor: "#1a1030",
        },
        dark: {
            primaryColor: "#1c1828",
            primaryTextColor: "#e8e2f4",
            primaryBorderColor: "#2e2848",
            lineColor: "#8a80a8",
            secondaryColor: "#1e1440",
            secondaryTextColor: "#e8e2f4",
            secondaryBorderColor: "#2e2848",
            tertiaryColor: "#13101c",
            tertiaryTextColor: "#e8e2f4",
            tertiaryBorderColor: "#2e2848",
            background: "#13101c",
            mainBkg: "#1c1828",
            textColor: "#e8e2f4",
            noteBkgColor: "#1e1440",
            noteTextColor: "#e8e2f4",
        },
    },
    red: {
        light: {
            primaryColor: "#fee2e2",
            primaryTextColor: "#1a0a0a",
            primaryBorderColor: "#e0b4b4",
            lineColor: "#8b6b6b",
            secondaryColor: "#fee2e2",
            secondaryTextColor: "#1a0a0a",
            secondaryBorderColor: "#e0b4b4",
            tertiaryColor: "#fef2f2",
            tertiaryTextColor: "#1a0a0a",
            tertiaryBorderColor: "#e0b4b4",
            background: "#fef2f2",
            mainBkg: "#fee2e2",
            textColor: "#1a0a0a",
            noteBkgColor: "#fee2e2",
            noteTextColor: "#1a0a0a",
        },
        dark: {
            primaryColor: "#241414",
            primaryTextColor: "#f0e8e8",
            primaryBorderColor: "#3a2020",
            lineColor: "#a08080",
            secondaryColor: "#2a1010",
            secondaryTextColor: "#f0e8e8",
            secondaryBorderColor: "#3a2020",
            tertiaryColor: "#1a0e0e",
            tertiaryTextColor: "#f0e8e8",
            tertiaryBorderColor: "#3a2020",
            background: "#1a0e0e",
            mainBkg: "#241414",
            textColor: "#f0e8e8",
            noteBkgColor: "#2a1010",
            noteTextColor: "#f0e8e8",
        },
    },
    orange: {
        light: {
            primaryColor: "#ffedd5",
            primaryTextColor: "#1a1008",
            primaryBorderColor: "#e0c8a8",
            lineColor: "#8a7260",
            secondaryColor: "#ffedd5",
            secondaryTextColor: "#1a1008",
            secondaryBorderColor: "#e0c8a8",
            tertiaryColor: "#fff7ed",
            tertiaryTextColor: "#1a1008",
            tertiaryBorderColor: "#e0c8a8",
            background: "#fff7ed",
            mainBkg: "#ffedd5",
            textColor: "#1a1008",
            noteBkgColor: "#ffedd5",
            noteTextColor: "#1a1008",
        },
        dark: {
            primaryColor: "#261a0e",
            primaryTextColor: "#f0ebe4",
            primaryBorderColor: "#3a2810",
            lineColor: "#a09080",
            secondaryColor: "#2e1c0a",
            secondaryTextColor: "#f0ebe4",
            secondaryBorderColor: "#3a2810",
            tertiaryColor: "#1a1208",
            tertiaryTextColor: "#f0ebe4",
            tertiaryBorderColor: "#3a2810",
            background: "#1a1208",
            mainBkg: "#261a0e",
            textColor: "#f0ebe4",
            noteBkgColor: "#2e1c0a",
            noteTextColor: "#f0ebe4",
        },
    },
    amber: {
        light: {
            primaryColor: "#fef3c7",
            primaryTextColor: "#1a1205",
            primaryBorderColor: "#e0cca0",
            lineColor: "#887550",
            secondaryColor: "#fef3c7",
            secondaryTextColor: "#1a1205",
            secondaryBorderColor: "#e0cca0",
            tertiaryColor: "#fffbeb",
            tertiaryTextColor: "#1a1205",
            tertiaryBorderColor: "#e0cca0",
            background: "#fffbeb",
            mainBkg: "#fef3c7",
            textColor: "#1a1205",
            noteBkgColor: "#fef3c7",
            noteTextColor: "#1a1205",
        },
        dark: {
            primaryColor: "#241c0e",
            primaryTextColor: "#f0ebe0",
            primaryBorderColor: "#3a2c10",
            lineColor: "#a09570",
            secondaryColor: "#2c2008",
            secondaryTextColor: "#f0ebe0",
            secondaryBorderColor: "#3a2c10",
            tertiaryColor: "#181208",
            tertiaryTextColor: "#f0ebe0",
            tertiaryBorderColor: "#3a2c10",
            background: "#181208",
            mainBkg: "#241c0e",
            textColor: "#f0ebe0",
            noteBkgColor: "#2c2008",
            noteTextColor: "#f0ebe0",
        },
    },
    yellow: {
        light: {
            primaryColor: "#fef9c3",
            primaryTextColor: "#1a1605",
            primaryBorderColor: "#ddd098",
            lineColor: "#857840",
            secondaryColor: "#fef9c3",
            secondaryTextColor: "#1a1605",
            secondaryBorderColor: "#ddd098",
            tertiaryColor: "#fefce8",
            tertiaryTextColor: "#1a1605",
            tertiaryBorderColor: "#ddd098",
            background: "#fefce8",
            mainBkg: "#fef9c3",
            textColor: "#1a1605",
            noteBkgColor: "#fef9c3",
            noteTextColor: "#1a1605",
        },
        dark: {
            primaryColor: "#221e0e",
            primaryTextColor: "#f0ece0",
            primaryBorderColor: "#383010",
            lineColor: "#a09860",
            secondaryColor: "#2a2408",
            secondaryTextColor: "#f0ece0",
            secondaryBorderColor: "#383010",
            tertiaryColor: "#16140a",
            tertiaryTextColor: "#f0ece0",
            tertiaryBorderColor: "#383010",
            background: "#16140a",
            mainBkg: "#221e0e",
            textColor: "#f0ece0",
            noteBkgColor: "#2a2408",
            noteTextColor: "#f0ece0",
        },
    },
    lime: {
        light: {
            primaryColor: "#ecfccb",
            primaryTextColor: "#0e1a08",
            primaryBorderColor: "#b8d898",
            lineColor: "#607840",
            secondaryColor: "#ecfccb",
            secondaryTextColor: "#0e1a08",
            secondaryBorderColor: "#b8d898",
            tertiaryColor: "#f7fee7",
            tertiaryTextColor: "#0e1a08",
            tertiaryBorderColor: "#b8d898",
            background: "#f7fee7",
            mainBkg: "#ecfccb",
            textColor: "#0e1a08",
            noteBkgColor: "#ecfccb",
            noteTextColor: "#0e1a08",
        },
        dark: {
            primaryColor: "#1a2210",
            primaryTextColor: "#e8f0e0",
            primaryBorderColor: "#283810",
            lineColor: "#88a860",
            secondaryColor: "#1c2808",
            secondaryTextColor: "#e8f0e0",
            secondaryBorderColor: "#283810",
            tertiaryColor: "#10160a",
            tertiaryTextColor: "#e8f0e0",
            tertiaryBorderColor: "#283810",
            background: "#10160a",
            mainBkg: "#1a2210",
            textColor: "#e8f0e0",
            noteBkgColor: "#1c2808",
            noteTextColor: "#e8f0e0",
        },
    },
    green: {
        light: {
            primaryColor: "#dcfce7",
            primaryTextColor: "#081a0e",
            primaryBorderColor: "#a8d8b8",
            lineColor: "#4a7858",
            secondaryColor: "#dcfce7",
            secondaryTextColor: "#081a0e",
            secondaryBorderColor: "#a8d8b8",
            tertiaryColor: "#f0fdf4",
            tertiaryTextColor: "#081a0e",
            tertiaryBorderColor: "#a8d8b8",
            background: "#f0fdf4",
            mainBkg: "#dcfce7",
            textColor: "#081a0e",
            noteBkgColor: "#dcfce7",
            noteTextColor: "#081a0e",
        },
        dark: {
            primaryColor: "#142018",
            primaryTextColor: "#e0f0e4",
            primaryBorderColor: "#1c3820",
            lineColor: "#68a878",
            secondaryColor: "#102818",
            secondaryTextColor: "#e0f0e4",
            secondaryBorderColor: "#1c3820",
            tertiaryColor: "#0c1610",
            tertiaryTextColor: "#e0f0e4",
            tertiaryBorderColor: "#1c3820",
            background: "#0c1610",
            mainBkg: "#142018",
            textColor: "#e0f0e4",
            noteBkgColor: "#102818",
            noteTextColor: "#e0f0e4",
        },
    },
    emerald: {
        light: {
            primaryColor: "#d1fae5",
            primaryTextColor: "#061a14",
            primaryBorderColor: "#a0d8c8",
            lineColor: "#408070",
            secondaryColor: "#d1fae5",
            secondaryTextColor: "#061a14",
            secondaryBorderColor: "#a0d8c8",
            tertiaryColor: "#ecfdf5",
            tertiaryTextColor: "#061a14",
            tertiaryBorderColor: "#a0d8c8",
            background: "#ecfdf5",
            mainBkg: "#d1fae5",
            textColor: "#061a14",
            noteBkgColor: "#d1fae5",
            noteTextColor: "#061a14",
        },
        dark: {
            primaryColor: "#12201a",
            primaryTextColor: "#daf0e8",
            primaryBorderColor: "#183828",
            lineColor: "#60a890",
            secondaryColor: "#0e2a1e",
            secondaryTextColor: "#daf0e8",
            secondaryBorderColor: "#183828",
            tertiaryColor: "#0a1612",
            tertiaryTextColor: "#daf0e8",
            tertiaryBorderColor: "#183828",
            background: "#0a1612",
            mainBkg: "#12201a",
            textColor: "#daf0e8",
            noteBkgColor: "#0e2a1e",
            noteTextColor: "#daf0e8",
        },
    },
    teal: {
        light: {
            primaryColor: "#ccfbf1",
            primaryTextColor: "#061a18",
            primaryBorderColor: "#98d8d0",
            lineColor: "#408078",
            secondaryColor: "#ccfbf1",
            secondaryTextColor: "#061a18",
            secondaryBorderColor: "#98d8d0",
            tertiaryColor: "#f0fdfa",
            tertiaryTextColor: "#061a18",
            tertiaryBorderColor: "#98d8d0",
            background: "#f0fdfa",
            mainBkg: "#ccfbf1",
            textColor: "#061a18",
            noteBkgColor: "#ccfbf1",
            noteTextColor: "#061a18",
        },
        dark: {
            primaryColor: "#12201e",
            primaryTextColor: "#daf0ec",
            primaryBorderColor: "#18382e",
            lineColor: "#60a8a0",
            secondaryColor: "#0e2a26",
            secondaryTextColor: "#daf0ec",
            secondaryBorderColor: "#18382e",
            tertiaryColor: "#0a1614",
            tertiaryTextColor: "#daf0ec",
            tertiaryBorderColor: "#18382e",
            background: "#0a1614",
            mainBkg: "#12201e",
            textColor: "#daf0ec",
            noteBkgColor: "#0e2a26",
            noteTextColor: "#daf0ec",
        },
    },
    cyan: {
        light: {
            primaryColor: "#cffafe",
            primaryTextColor: "#061a1e",
            primaryBorderColor: "#98d0d8",
            lineColor: "#407880",
            secondaryColor: "#cffafe",
            secondaryTextColor: "#061a1e",
            secondaryBorderColor: "#98d0d8",
            tertiaryColor: "#ecfeff",
            tertiaryTextColor: "#061a1e",
            tertiaryBorderColor: "#98d0d8",
            background: "#ecfeff",
            mainBkg: "#cffafe",
            textColor: "#061a1e",
            noteBkgColor: "#cffafe",
            noteTextColor: "#061a1e",
        },
        dark: {
            primaryColor: "#101e22",
            primaryTextColor: "#daeef0",
            primaryBorderColor: "#183038",
            lineColor: "#60a0a8",
            secondaryColor: "#0e2228",
            secondaryTextColor: "#daeef0",
            secondaryBorderColor: "#183038",
            tertiaryColor: "#0a1418",
            tertiaryTextColor: "#daeef0",
            tertiaryBorderColor: "#183038",
            background: "#0a1418",
            mainBkg: "#101e22",
            textColor: "#daeef0",
            noteBkgColor: "#0e2228",
            noteTextColor: "#daeef0",
        },
    },
    sky: {
        light: {
            primaryColor: "#e0f2fe",
            primaryTextColor: "#08141e",
            primaryBorderColor: "#a0c8e0",
            lineColor: "#406880",
            secondaryColor: "#e0f2fe",
            secondaryTextColor: "#08141e",
            secondaryBorderColor: "#a0c8e0",
            tertiaryColor: "#f0f9ff",
            tertiaryTextColor: "#08141e",
            tertiaryBorderColor: "#a0c8e0",
            background: "#f0f9ff",
            mainBkg: "#e0f2fe",
            textColor: "#08141e",
            noteBkgColor: "#e0f2fe",
            noteTextColor: "#08141e",
        },
        dark: {
            primaryColor: "#101c24",
            primaryTextColor: "#dce8f0",
            primaryBorderColor: "#182c3a",
            lineColor: "#6098b0",
            secondaryColor: "#0e2030",
            secondaryTextColor: "#dce8f0",
            secondaryBorderColor: "#182c3a",
            tertiaryColor: "#0a1218",
            tertiaryTextColor: "#dce8f0",
            tertiaryBorderColor: "#182c3a",
            background: "#0a1218",
            mainBkg: "#101c24",
            textColor: "#dce8f0",
            noteBkgColor: "#0e2030",
            noteTextColor: "#dce8f0",
        },
    },
    blue: {
        light: {
            primaryColor: "#dbeafe",
            primaryTextColor: "#0a1028",
            primaryBorderColor: "#a0b8e0",
            lineColor: "#506088",
            secondaryColor: "#dbeafe",
            secondaryTextColor: "#0a1028",
            secondaryBorderColor: "#a0b8e0",
            tertiaryColor: "#eff6ff",
            tertiaryTextColor: "#0a1028",
            tertiaryBorderColor: "#a0b8e0",
            background: "#eff6ff",
            mainBkg: "#dbeafe",
            textColor: "#0a1028",
            noteBkgColor: "#dbeafe",
            noteTextColor: "#0a1028",
        },
        dark: {
            primaryColor: "#141c2e",
            primaryTextColor: "#dce0f0",
            primaryBorderColor: "#1c2840",
            lineColor: "#7088b0",
            secondaryColor: "#101c38",
            secondaryTextColor: "#dce0f0",
            secondaryBorderColor: "#1c2840",
            tertiaryColor: "#0c1020",
            tertiaryTextColor: "#dce0f0",
            tertiaryBorderColor: "#1c2840",
            background: "#0c1020",
            mainBkg: "#141c2e",
            textColor: "#dce0f0",
            noteBkgColor: "#101c38",
            noteTextColor: "#dce0f0",
        },
    },
    indigo: {
        light: {
            primaryColor: "#e0e7ff",
            primaryTextColor: "#0e0c28",
            primaryBorderColor: "#a8a0d8",
            lineColor: "#585080",
            secondaryColor: "#e0e7ff",
            secondaryTextColor: "#0e0c28",
            secondaryBorderColor: "#a8a0d8",
            tertiaryColor: "#eef2ff",
            tertiaryTextColor: "#0e0c28",
            tertiaryBorderColor: "#a8a0d8",
            background: "#eef2ff",
            mainBkg: "#e0e7ff",
            textColor: "#0e0c28",
            noteBkgColor: "#e0e7ff",
            noteTextColor: "#0e0c28",
        },
        dark: {
            primaryColor: "#1a1828",
            primaryTextColor: "#e0def0",
            primaryBorderColor: "#282440",
            lineColor: "#8080b0",
            secondaryColor: "#181440",
            secondaryTextColor: "#e0def0",
            secondaryBorderColor: "#282440",
            tertiaryColor: "#0e0c1c",
            tertiaryTextColor: "#e0def0",
            tertiaryBorderColor: "#282440",
            background: "#0e0c1c",
            mainBkg: "#1a1828",
            textColor: "#e0def0",
            noteBkgColor: "#181440",
            noteTextColor: "#e0def0",
        },
    },
    violet: {
        light: {
            primaryColor: "#ede9fe",
            primaryTextColor: "#100c28",
            primaryBorderColor: "#b8a8e0",
            lineColor: "#605080",
            secondaryColor: "#ede9fe",
            secondaryTextColor: "#100c28",
            secondaryBorderColor: "#b8a8e0",
            tertiaryColor: "#f5f3ff",
            tertiaryTextColor: "#100c28",
            tertiaryBorderColor: "#b8a8e0",
            background: "#f5f3ff",
            mainBkg: "#ede9fe",
            textColor: "#100c28",
            noteBkgColor: "#ede9fe",
            noteTextColor: "#100c28",
        },
        dark: {
            primaryColor: "#1c1828",
            primaryTextColor: "#e4e0f0",
            primaryBorderColor: "#2c2448",
            lineColor: "#8878a8",
            secondaryColor: "#1c1440",
            secondaryTextColor: "#e4e0f0",
            secondaryBorderColor: "#2c2448",
            tertiaryColor: "#100e1c",
            tertiaryTextColor: "#e4e0f0",
            tertiaryBorderColor: "#2c2448",
            background: "#100e1c",
            mainBkg: "#1c1828",
            textColor: "#e4e0f0",
            noteBkgColor: "#1c1440",
            noteTextColor: "#e4e0f0",
        },
    },
    purple: {
        light: {
            primaryColor: "#f3e8ff",
            primaryTextColor: "#140a28",
            primaryBorderColor: "#c0a0e0",
            lineColor: "#684888",
            secondaryColor: "#f3e8ff",
            secondaryTextColor: "#140a28",
            secondaryBorderColor: "#c0a0e0",
            tertiaryColor: "#faf5ff",
            tertiaryTextColor: "#140a28",
            tertiaryBorderColor: "#c0a0e0",
            background: "#faf5ff",
            mainBkg: "#f3e8ff",
            textColor: "#140a28",
            noteBkgColor: "#f3e8ff",
            noteTextColor: "#140a28",
        },
        dark: {
            primaryColor: "#201828",
            primaryTextColor: "#e8e0f4",
            primaryBorderColor: "#30204a",
            lineColor: "#9070b0",
            secondaryColor: "#201040",
            secondaryTextColor: "#e8e0f4",
            secondaryBorderColor: "#30204a",
            tertiaryColor: "#14101c",
            tertiaryTextColor: "#e8e0f4",
            tertiaryBorderColor: "#30204a",
            background: "#14101c",
            mainBkg: "#201828",
            textColor: "#e8e0f4",
            noteBkgColor: "#201040",
            noteTextColor: "#e8e0f4",
        },
    },
    fuchsia: {
        light: {
            primaryColor: "#fae8ff",
            primaryTextColor: "#1a0a20",
            primaryBorderColor: "#d8a0e0",
            lineColor: "#804888",
            secondaryColor: "#fae8ff",
            secondaryTextColor: "#1a0a20",
            secondaryBorderColor: "#d8a0e0",
            tertiaryColor: "#fdf4ff",
            tertiaryTextColor: "#1a0a20",
            tertiaryBorderColor: "#d8a0e0",
            background: "#fdf4ff",
            mainBkg: "#fae8ff",
            textColor: "#1a0a20",
            noteBkgColor: "#fae8ff",
            noteTextColor: "#1a0a20",
        },
        dark: {
            primaryColor: "#241828",
            primaryTextColor: "#f0e0f0",
            primaryBorderColor: "#38204a",
            lineColor: "#a068a8",
            secondaryColor: "#281040",
            secondaryTextColor: "#f0e0f0",
            secondaryBorderColor: "#38204a",
            tertiaryColor: "#18101c",
            tertiaryTextColor: "#f0e0f0",
            tertiaryBorderColor: "#38204a",
            background: "#18101c",
            mainBkg: "#241828",
            textColor: "#f0e0f0",
            noteBkgColor: "#281040",
            noteTextColor: "#f0e0f0",
        },
    },
    pink: {
        light: {
            primaryColor: "#fce7f3",
            primaryTextColor: "#1c0a18",
            primaryBorderColor: "#e0a8c8",
            lineColor: "#886070",
            secondaryColor: "#fce7f3",
            secondaryTextColor: "#1c0a18",
            secondaryBorderColor: "#e0a8c8",
            tertiaryColor: "#fdf2f8",
            tertiaryTextColor: "#1c0a18",
            tertiaryBorderColor: "#e0a8c8",
            background: "#fdf2f8",
            mainBkg: "#fce7f3",
            textColor: "#1c0a18",
            noteBkgColor: "#fce7f3",
            noteTextColor: "#1c0a18",
        },
        dark: {
            primaryColor: "#241420",
            primaryTextColor: "#f0e0ec",
            primaryBorderColor: "#3a1c30",
            lineColor: "#a87090",
            secondaryColor: "#2c1028",
            secondaryTextColor: "#f0e0ec",
            secondaryBorderColor: "#3a1c30",
            tertiaryColor: "#1a0e18",
            tertiaryTextColor: "#f0e0ec",
            tertiaryBorderColor: "#3a1c30",
            background: "#1a0e18",
            mainBkg: "#241420",
            textColor: "#f0e0ec",
            noteBkgColor: "#2c1028",
            noteTextColor: "#f0e0ec",
        },
    },
    rose: {
        light: {
            primaryColor: "#ffe4e6",
            primaryTextColor: "#1c0a10",
            primaryBorderColor: "#e0a8b0",
            lineColor: "#886068",
            secondaryColor: "#ffe4e6",
            secondaryTextColor: "#1c0a10",
            secondaryBorderColor: "#e0a8b0",
            tertiaryColor: "#fff1f2",
            tertiaryTextColor: "#1c0a10",
            tertiaryBorderColor: "#e0a8b0",
            background: "#fff1f2",
            mainBkg: "#ffe4e6",
            textColor: "#1c0a10",
            noteBkgColor: "#ffe4e6",
            noteTextColor: "#1c0a10",
        },
        dark: {
            primaryColor: "#24141a",
            primaryTextColor: "#f0e0e4",
            primaryBorderColor: "#3a1c24",
            lineColor: "#a87080",
            secondaryColor: "#2c1018",
            secondaryTextColor: "#f0e0e4",
            secondaryBorderColor: "#3a1c24",
            tertiaryColor: "#1a0e12",
            tertiaryTextColor: "#f0e0e4",
            tertiaryBorderColor: "#3a1c24",
            background: "#1a0e12",
            mainBkg: "#24141a",
            textColor: "#f0e0e4",
            noteBkgColor: "#2c1018",
            noteTextColor: "#f0e0e4",
        },
    },
};

// 현재 스킴과 다크모드에서 Mermaid 설정 생성
export function getMermaidConfig(
    scheme: string | null,
    isDark: boolean
): {
    theme: string;
    themeVariables: Record<string, string | number | boolean>;
} {
    const validScheme: ColorScheme =
        scheme && scheme in MERMAID_THEMES ? (scheme as ColorScheme) : "slate";
    const schemeThemes = MERMAID_THEMES[validScheme];
    const themeVars = isDark ? schemeThemes.dark : schemeThemes.light;
    return {
        theme: "base",
        themeVariables: {
            ...themeVars,
            fontSize: "18px",
            fontFamily: "inherit",
            darkMode: isDark,
        },
    };
}
